// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture2D<float4> Result;

int2 Resolution;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    float x = (float)id.x / (float)Resolution.x;
    float y = (float)id.y / (float)Resolution.y;

    Result[id.xy] = float4(x, y, 0, 0);
}
