// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

struct Ball
{
    uint id;
    float3 position;
    float3 velocity;
};

RWStructuredBuffer<Ball> BallBuffer;

float3 Gravity;
float DeltaTime;

[numthreads(32,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    Ball ball = BallBuffer[id.x];

    ball.velocity += Gravity * DeltaTime;
    ball.position += ball.velocity * DeltaTime;

    BallBuffer[id.x] = ball;
}
